version: 0.2

env:
  parameter-store:
    registry_username: registry_username
    registry_password: registry_password
    registry_url: registry_url
    repo_username: repo_username
    registry_region: registry_region
    registry_accountid: registry_accountid
phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r simple-python-app/requirements.txt
  build:
    commands:
      - echo "Running tests..."
      - cd simple-python-app/
      - aws ecr get-login-password --region "$registry_region" | docker login --username "$registry_username" --password-stdin "$registry_accountid".dkr.ecr."$registry_region".amazonaws.com
      - echo "Building Docker image..."
      - echo "$registry_password" | docker login -u "$registry_username" --password-stdin "$registry_url"
      - docker build -t "$registry_url:latest" .
      - docker push "$registry_url:latest"
  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*'
  base-directory: simple-python-app
