version: 0.2

env:
  parameter-store:
    registry_username: registry_username
    registry_password: registry_password
    registry_url: registry_url
    repo_username: repo_username
phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r simple-python-app/requirements.txt
  build:
    commands:
      - echo "Running tests..."
      - cd simple-python-app/
      - echo aws ecr get-login-password --region ap-south-1 | docker login -u "$registry_username" --password-stdin "$registry_url"
      - echo "Building Docker image..."
      - echo "$registry_password" | docker login -u "$registry_username" --password-stdin "$registry_url"
      - docker build -t "$registry_url:latest" .
      - docker push "$registry_url:latest"
  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*'
  base-directory: ../simple-python-app
